Add Neutron pkg and test double, update Glance
go-goose/goose pull request #30
Opened 2016-11-07 20:20 UTC by hmlanigan

Add Neutron package and test service, functions related to Networks, Subnets, FloatingIPs, SecurityGroups, SecurityGroupRules.  Neutron and Nova test services share Network, FloatingIP and SecurityGroup data for OpenStack service.

2016-11-11 13:37 UTC, bz2 commented on glance/glance.go
> +// ImageDetailV2 describes extended information about an image for API v2.0.
I know the upstream docs move around a  bit, but I'd like a url reference in the comment here so it's clearer what the various fields in the struct mean.

2016-11-11 14:49 UTC, bz2 requested changes
Thanks for this!

I have a bunch of comments inline, not all of them are actionable changes, please poke me if anything is unclear or if you disagree, am happy to discuss design questions.

Skimmed the test service chunks a bit faster than the rest of the code, and yes, I do feel your pain here. Attempting to have a setup that sort-of runs 'live' tests rather than more focused unit testing leads to a crazy amount of test code to support a small quantity of business logic.

Bigger questions on the PR overall:
- What versions of openstack are expecting the neutron code to work with... L upwards? What did you test against when developing?
- How is a user of the goose library expected to select between nova networking and neutron? In other words, if they just want to make a security group, what should their code do to select the right set of functions for their openstack? Or, do we just think everyone should be using neutron regardless these days?

I am mgz on irc/freenode if you want to poke me in real time.

2016-11-11 14:49 UTC, bz2 commented on glance/glance.go
> +// ImageDetailV2 describes extended information about an image for API v2.0.
I know the upstream docs move around a bit, but I'd like a url reference in the comment here so it's clearer what the various fields in the struct mean.

2016-11-11 14:49 UTC, bz2 commented on neutron/local_test.go
> +	s.retryErrorCount = 0
Why is setting this to zero required? Without this, can just omit SetUpTest and TearDownTest on localLiveSuite and LiveTests?

2016-11-11 14:49 UTC, bz2 commented on neutron/live_test.go
> +	firstNetwork := networks[0]
Test hasn't actually asserted this one or more networks returned? Is that just a given anyway?

2016-11-11 14:49 UTC, bz2 commented on neutron/live_test.go
> +	firstSubnet := subnets[0]
Same issue, will there always be one ore more subnets?

2016-11-11 14:49 UTC, bz2 commented on neutron/live_test.go
> +		c.Assert(subnet.Cidr, gc.Matches, `\d{1,3}(\.+\d{1,3}){3}\/\d+`)
Are subnets always ipv4?

2016-11-11 14:49 UTC, bz2 commented on neutron/live_test.go
> +	c.Check(ip.IP, gc.Not(gc.Equals), "")
If any of these following checks fails, the floating ip remains allocated?

2016-11-11 14:49 UTC, bz2 commented on neutron/live_test.go
> +	defer s.neutron.DeleteSecurityGroupV2(newSecGrp.Id)
This should really be a function that also checks the error return from DeleteSecurityGroupV2.

2016-11-11 14:49 UTC, bz2 commented on neutron/live_test.go
> +	defer s.neutron.DeleteSecurityGroupV2(newSecGrp.Id)
Same thing with err being unchecked.

2016-11-11 14:49 UTC, bz2 commented on neutron/live_test.go
> +	errorSecGrps, err := s.neutron.SecurityGroupByNameV2("deadbeef")
I agree that's an unlike name, but I'd generally use something like 'nonexisistantgroup' so any error messages are clearer.

2016-11-11 14:49 UTC, bz2 commented on neutron/live_test.go
> +	// Create and find a SecurityGroup with spaces in the name
This could just be a seperate test.

2016-11-11 14:49 UTC, bz2 commented on neutron/local_test.go
> +// Additional tests to be run against the service double only go here.
This comment is not a doc comment on the method below. Delete it?

2016-11-11 14:49 UTC, bz2 commented on neutron/neutron.go
> +	Name              string   // User-provided name for the network range
Doesn't this need `json:"name"` as well?

2016-11-11 14:49 UTC, bz2 commented on neutron/neutron.go
> +	Name            string        // User-provided name for the subnet
Also needs `json:"name"`?

2016-11-11 14:49 UTC, bz2 commented on neutron/neutron.go
> +	if strings.Contains(name, " ") {
Can't we do proper url encoding instead?

2016-11-11 14:49 UTC, bz2 commented on neutron/neutron.go
> +	Id          string
I'd give json lowercased names for these as well so they reserialise lowercased.

2016-11-11 14:49 UTC, bz2 commented on neutron/neutron.go
> +		SecurityGroupV2 struct {
With omitempty on the rules, tenantid, and id, could use the normal SecurityGroupV2 struct.

2016-11-11 14:49 UTC, bz2 commented on neutron/neutron.go
> +// RuleInfo allows the callers of CreateSecurityGroupRuleV2() to
RuleInfoV2.

2016-11-11 14:49 UTC, bz2 commented on testservices/neutronmodel/neutronmodel.go
> +			AvailabilityZones: []string{"deadbeef"},
I'd use a string like 'another-az' rather than the deadbeef.

2016-11-11 14:49 UTC, bz2 commented on testservices/neutronmodel/neutronmodel.go
> +	id1 := id * 999
Multiply rather than mask/add for unique ids is interesting, test output might get some very large ints. :)

2016-11-11 14:49 UTC, bz2 commented on testservices/neutronservice/service_http.go
> +	errBadRequest2 = &errorResponse{
I'd try and give these clearer names, eg errBadRequestMalformedURL/errBadRequestIncorrect/errBadRequestMalformedBody.

2016-11-11 14:49 UTC, bz2 commented on testservices/neutronservice/service_http.go
> +		`{"version": {"status": "CURRENT", "updated": "2011-01-21T11` +
Well, isn't this a nice error.

2016-11-11 14:49 UTC, bz2 commented on testservices/novaservice/service.go
> +	if strings.Contains(address, ":") {
Could use net.IP to do a more sane determination of 4 vs 6, but doesn't matter much for test code.

2016-11-11 14:49 UTC, bz2 commented on testservices/novaservice/service_http_test.go
> +var _ = gc.Suite(&NovaHTTPSSuite{HTTPSuite: httpsuite.HTTPSuite{UseTLS: true}, useNeutronNetworking: true})
It's an arbitrary pick that the https varient uses the new codepaths and the other doesn't? I suspect that doing a matrix of these gets us very little though with how the testing is structured.

2016-11-11 14:49 UTC, bz2 commented on testservices/novaservice/service_test.go
> +var _ = gc.Suite(&NovaSuite{useNeutronNetworking: false})
Okay, so these tests just do both paths.

2016-11-11 16:10 UTC, hmlanigan commented
We're expecting this code to work with IceHouse and forward, until the APIs are deprecated or new ones revealed as better.  Primary testing has been done against Mitaka.  And a tiny bit against Ice House.  Ice House is the earliest OpenStack release supported with juju 2.0.

Ideally all OpenStack deployments are using Neutron networking at this point.  However I can't guarantee that.  Nor do I fully know which other projects are using go-goose.  From a package perspective I chose to leave the Nova networking in place as the code doesn't conflict.   

Developers using using goose will have to choose the Neutron functions rather than the Nova functions if they want to use Neutron networking.  The function names are very similar, so should be easy to find.  Functions within the Nova package which aren't directly related to creating or listing floating ips, security groups and rules, or networks continue to function independently of Neutron.  Such as nova.AddServerFloatingIP().

However if a developer is using the OpenStack test service, they will be using neutron networking and the Nova networking functions won't work.  If they use the Nova test service, a choice can be made on whether to use nova or neutron.

2016-11-11 16:17 UTC, hmlanigan commented on glance/glance.go
> +// ImageDetailV2 describes extended information about an image for API v2.0.
The url is at the top of the page.  I'm adding one for the image functions utilizing the compute server as well.

2016-11-11 17:30 UTC, hmlanigan commented on neutron/local_test.go
> +	s.retryErrorCount = 0
You've caught me doing a copy, paste, modify from the nova tests to create the neutron ones and not catching all of the clean up work.  I removed code related to retryErrorCount and retryErrorCountToSend.

2016-11-11 17:30 UTC, hmlanigan commented on neutron/local_test.go
> +// Additional tests to be run against the service double only go here.
yes

2016-11-11 17:33 UTC, hmlanigan commented on neutron/live_test.go
> +	c.Check(ip.IP, gc.Not(gc.Equals), "")
added defer DeleteFloatingIPV2()

2016-11-11 18:53 UTC, hmlanigan commented on neutron/live_test.go
> +	firstNetwork := networks[0]
For the test doubles, there will always be a network.  If testing live, we need an existing network to run the test, as we don't create any.  Adding an error if no networks exist.

2016-11-11 18:54 UTC, hmlanigan commented on neutron/live_test.go
> +	firstSubnet := subnets[0]
same answer as for networks

2016-11-11 19:30 UTC, hmlanigan commented on neutron/live_test.go
> +		c.Assert(subnet.Cidr, gc.Matches, `\d{1,3}(\.+\d{1,3}){3}\/\d+`)
No. IPv4 is just what is used by the code I'm testing against.  Updating to use net.ParseCidr().  Adding IPv6 subnet to test double.

2016-11-11 19:46 UTC, hmlanigan commented on neutron/live_test.go
> +	errorSecGrps, err := s.neutron.SecurityGroupByNameV2("deadbeef")
done.

2016-11-11 19:48 UTC, hmlanigan commented on neutron/live_test.go
> +	// Create and find a SecurityGroup with spaces in the name
most of the tests could be broken up into multiple tests.  i'm going to leave this as is.

2016-11-11 19:50 UTC, hmlanigan commented on neutron/neutron.go
> +	Name              string   // User-provided name for the network range
the json parsing seems to be okay converting if the capitalization is different between the structures.  However the code isn't consistent about when to specify json:"", so I'll add it to all.

2016-11-11 19:51 UTC, hmlanigan commented on neutron/neutron.go
> +	Name            string        // User-provided name for the subnet
see above

2016-11-11 20:00 UTC, hmlanigan commented on neutron/neutron.go
> +		SecurityGroupV2 struct {
A rules array isn't optional when a SecurityGroup is returned from neutron, trying to stay consistent with the API.

2016-11-11 20:00 UTC, hmlanigan commented on neutron/neutron.go
> +// RuleInfo allows the callers of CreateSecurityGroupRuleV2() to
done

2016-11-11 20:01 UTC, hmlanigan commented on testservices/neutronmodel/neutronmodel.go
> +			AvailabilityZones: []string{"deadbeef"},
resolved

2016-11-11 20:02 UTC, hmlanigan commented on testservices/neutronmodel/neutronmodel.go
> +	id1 := id * 999
luckily i wrote the test code.  :-)

2016-11-11 20:05 UTC, hmlanigan commented on testservices/neutronservice/service_http.go
> +		`{"version": {"status": "CURRENT", "updated": "2011-01-21T11` +
and isn't used... removing.

2016-11-11 21:17 UTC, hmlanigan commented on neutron/neutron.go
> +	if strings.Contains(name, " ") {
found url.QueryEscape(), using that instead.

2016-11-11 21:23 UTC, hmlanigan commented on testservices/novaservice/service_http_test.go
> +var _ = gc.Suite(&NovaHTTPSSuite{HTTPSuite: httpsuite.HTTPSuite{UseTLS: true}, useNeutronNetworking: true})
Yes, it is an arbitrary pick, however I saw no reason to double the number of tests to complete the matrix.  The two code paths are unrelated.

2016-11-11 21:26 UTC, hmlanigan commented on testservices/neutronservice/service_http.go
> +	errBadRequest2 = &errorResponse{
done

2016-11-11 21:40 UTC, hmlanigan commented on neutron/live_test.go
> +	defer s.neutron.DeleteSecurityGroupV2(newSecGrp.Id)
done

2016-11-11 21:40 UTC, hmlanigan commented on neutron/live_test.go
> +	defer s.neutron.DeleteSecurityGroupV2(newSecGrp.Id)
done

2016-11-15 18:30 UTC, bz2 approved these changes
Thanks for making the changes, I think this is good to go now.

2016-11-15 18:31 UTC, bz2 commented
$$merge$$

2016-11-15 18:36 UTC, merged