Allow delete non-existent security group.
go-goose/goose pull request #86
Opened 2020-06-25 05:50 UTC by howbazaar

Getting a not found error when deleting something should be a silent success.

Addresses https://bugs.launchpad.net/juju/+bug/1864564

2020-06-25 05:50 UTC, howbazaar commented
I couldn't find any existing tests for this.

2020-06-25 08:03 UTC, SimonRichardson requested changes
I don't think this right, especially for a client. Instead, we should return an `errors.NotFound` and then correctly handle the `NotFound` error inside the Openstack firewaller.

2020-06-25 08:58 UTC, SimonRichardson commented
See: https://github.com/juju/juju/pull/11756

2020-06-26 02:13 UTC, howbazaar commented
Fair call.

2020-06-26 02:13 UTC, closed without merging